### ISSUE TITLE
Archicad 19 Update

### ISSUE THREAD

**Issue by lolipale** [autopkg/robperc-recipes#3]
Hello
Archicad 19 updates don't run correctly. I guess that Graphisoft has changed something in the download url.
I have a request : Is it possible to add in your recipe the possibility to choose the language ?
I will like download Archicad in French (FRA) but, for example, all packages of goodies in french languages haven't the same pattern of goodies USA
Thanks for your help and support

**Comment by robperc** [comment]
I've fixed the issue with the updates recipe, the summary for the commit can be found here:
https://github.com/autopkg/robperc-recipes/commit/2c5ce6e46db637b5f3a2d84c99ff061c7ef10c9f

I've updated the base AC19 recipe and the AC19 goodies recipe to allow for the overriding of the country code for downloads for languages other than english. This appears to work for the base AC19 recipe but not the goodies, if you'd like to figure out the pattern for non-US english download URLs for that recipe and get it working feel free to submit a pull request. The summaries for these commits can be found here:
https://github.com/autopkg/robperc-recipes/commit/0030025430dda549421d0d2ea49c099006c71028
https://github.com/autopkg/robperc-recipes/commit/6abf1f4e3be98daf6919259b69d164bd5c227b63
